language: node_js
node_js:
  - "16"
stages:
  - Code Quality
  - Unit Tests
  - Integration Tests

script: skip

jobs:
  include:
    - stage: Code Quality
      if: branch = main OR type = pull_request
      script:
        - yarn lint
        - yarn audit --prod --level=critical
    - stage: Unit Tests
      if: branch = main OR type = pull_request
      before_install: yarn global add codecov
      script: yarn test --coverage
      after_success: codecov
    - stage: Integration Tests
      if: branch = main OR type = pull_request
      script: yarn test:integration
cache:
  yarn: true
notifications:
  email: false
